### ISSUE TITLE
data.azurecaf_name result is without seperator

### ISSUE THREAD

**Issue by Kumar9676** [claranet/terraform-azurerm-storage-account#10]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.4.5

### AzureRM Provider Version

3.83.0

### Affected Resource(s)/Data Source(s)

azurerm 7.7.0 for storage-account

### Terraform Configuration Files

```hcl
module "storage-account" {
  source  = "claranet/storage-account/azurerm"
  version = "7.7.0"

  # insert the 7 required variables here
  location       = module.azure_region.location
  location_short = ""
  client_name    = var.client_name
  environment    = var.environment
  stack          = var.stack
  name_prefix = var.region_short_prefix
  use_caf_naming = true

  resource_group_name = module.rg.resource_group_name

  #allowed_cidrs = [format("%s/32", data.http.my_ip.body)]
  
  account_kind = "StorageV2"
  account_replication_type = "LRS"
  access_tier = "Hot"
  account_tier = "Standard"

  logs_destinations_ids = []

  containers = [
    {
      name = "raw"
    },
    {
      name = "curated"
      # container_access_type = "blob"
    }
  ]

  network_rules_enabled = true
  hns_enabled = true
  nfsv3_enabled = false
  min_tls_version = "TLS1_2"
  subnet_ids = [  ]

}
```

### Debug Output/Panic Output

```shell
# module.storage-account.azurerm_storage_account.storage will be created
  + resource "azurerm_storage_account" "storage" {
      + access_tier                       = "Hot"
      + account_kind                      = "StorageV2"
      + account_replication_type          = "LRS"
      + account_tier                      = "Standard"
      + allow_nested_items_to_be_public   = false
      + cross_tenant_replication_enabled  = true
      + default_to_oauth_authentication   = false
      + enable_https_traffic_only         = true
      + id                                = (known after apply)
      + infrastructure_encryption_enabled = false
      + is_hns_enabled                    = true
      + large_file_share_enabled          = true
      + location                          = "southeastasia"
      + min_tls_version                   = "TLS1_2"
      + name                              = "cistmartechapacsandbox"
      + nfsv3_enabled                     = false
      + primary_access_key                = (sensitive value)
      + primary_blob_connection_string    = (sensitive value)
      + primary_blob_endpoint             = (known after apply)
      + primary_blob_host                 = (known after apply)
      + primary_connection_string         = (sensitive value)
      + primary_dfs_endpoint              = (known after apply)
      + primary_dfs_host                  = (known after apply)
      + primary_file_endpoint             = (known after apply)
      + primary_file_host                 = (known after apply)
      + primary_location                  = (known after apply)
      + primary_queue_endpoint            = (known after apply)
      + primary_queue_host                = (known after apply)
      + primary_table_endpoint            = (known after apply)
      + primary_table_host                = (known after apply)
      + primary_web_endpoint              = (known after apply)
      + primary_web_host                  = (known after apply)
      + public_network_access_enabled     = true
      + queue_encryption_key_type         = "Service"
      + resource_group_name               = "ci-rg-martech-apac-sandbox"
      + secondary_access_key              = (sensitive value)
      + secondary_blob_connection_string  = (sensitive value)
      + secondary_blob_endpoint           = (known after apply)
      + secondary_blob_host               = (known after apply)
      + secondary_connection_string       = (sensitive value)
      + secondary_dfs_endpoint            = (known after apply)
      + secondary_dfs_host                = (known after apply)
      + secondary_file_endpoint           = (known after apply)
      + secondary_file_host               = (known after apply)
      + secondary_location                = (known after apply)
      + secondary_queue_endpoint          = (known after apply)
      + secondary_queue_host              = (known after apply)
      + secondary_table_endpoint          = (known after apply)
      + secondary_table_host              = (known after apply)
      + secondary_web_endpoint            = (known after apply)
      + secondary_web_host                = (known after apply)
      + sftp_enabled                      = false
      + shared_access_key_enabled         = true
      + table_encryption_key_type         = "Service"
      + tags                              = {
          + "env"   = "sandbox"
          + "stack" = "martech"
        }

      + blob_properties {
          + change_feed_enabled      = true
          + default_service_version  = (known after apply)
          + last_access_time_enabled = true
          + versioning_enabled       = true

          + container_delete_retention_policy {
              + days = 30
            }

          + delete_retention_policy {
              + days = 30
            }

          + restore_policy {
              + days = 29
            }
        }

      + identity {
          + principal_id = (known after apply)
          + tenant_id    = (known after apply)
          + type         = "SystemAssigned"
        }

      + queue_properties {
          + logging {
              + delete                = true
              + read                  = true
              + retention_policy_days = 10
              + version               = "1.0"
              + write                 = true
            }
        }
    }
```

### Expected Behaviour

# module.storage-account.azurerm_storage_account.storage will be created
  + resource "azurerm_storage_account" "storage" {
      + access_tier                       = "Hot"
      + account_kind                      = "StorageV2"
      + account_replication_type          = "LRS"
      + account_tier                      = "Standard"
      + allow_nested_items_to_be_public   = false
      + cross_tenant_replication_enabled  = true
      + default_to_oauth_authentication   = false
      + enable_https_traffic_only         = true
      + id                                = (known after apply)
      + infrastructure_encryption_enabled = false
      + is_hns_enabled                    = true
      + large_file_share_enabled          = true
      + location                          = "southeastasia"
      + min_tls_version                   = "TLS1_2"
      + name                              = "**ci-st-martech-apac-sandbox**"
      + nfsv3_enabled                     = false
      + primary_access_key                = (sensitive value)
      + primary_blob_connection_string    = (sensitive value)
      + primary_blob_endpoint             = (known after apply)
      + primary_blob_host                 = (known after apply)
      + primary_connection_string         = (sensitive value)
      + primary_dfs_endpoint              = (known after apply)
      + primary_dfs_host                  = (known after apply)
      + primary_file_endpoint             = (known after apply)
      + primary_file_host                 = (known after apply)
      + primary_location                  = (known after apply)
      + primary_queue_endpoint            = (known after apply)
      + primary_queue_host                = (known after apply)
      + primary_table_endpoint            = (known after apply)
      + primary_table_host                = (known after apply)
      + primary_web_endpoint              = (known after apply)
      + primary_web_host                  = (known after apply)
      + public_network_access_enabled     = true
      + queue_encryption_key_type         = "Service"
      + resource_group_name               = "ci-rg-martech-apac-sandbox"
      + secondary_access_key              = (sensitive value)
      + secondary_blob_connection_string  = (sensitive value)
      + secondary_blob_endpoint           = (known after apply)
      + secondary_blob_host               = (known after apply)
      + secondary_connection_string       = (sensitive value)
      + secondary_dfs_endpoint            = (known after apply)
      + secondary_dfs_host                = (known after apply)
      + secondary_file_endpoint           = (known after apply)
      + secondary_file_host               = (known after apply)
      + secondary_location                = (known after apply)
      + secondary_queue_endpoint          = (known after apply)
      + secondary_queue_host              = (known after apply)
      + secondary_table_endpoint          = (known after apply)
      + secondary_table_host              = (known after apply)
      + secondary_web_endpoint            = (known after apply)
      + secondary_web_host                = (known after apply)
      + sftp_enabled                      = false
      + shared_access_key_enabled         = true
      + table_encryption_key_type         = "Service"
      + tags                              = {
          + "env"   = "sandbox"
          + "stack" = "martech"
        }

      + blob_properties {
          + change_feed_enabled      = true
          + default_service_version  = (known after apply)
          + last_access_time_enabled = true
          + versioning_enabled       = true

          + container_delete_retention_policy {
              + days = 30
            }

          + delete_retention_policy {
              + days = 30
            }

          + restore_policy {
              + days = 29
            }
        }

      + identity {
          + principal_id = (known after apply)
          + tenant_id    = (known after apply)
          + type         = "SystemAssigned"
        }

      + queue_properties {
          + logging {
              + delete                = true
              + read                  = true
              + retention_policy_days = 10
              + version               = "1.0"
              + write                 = true
            }
        }
    }

### Actual Behaviour

Storage Account Name created - cistmartechapacsandbox

### Steps to Reproduce

terraform init
terraform plan

**Comment by BzSpi** [comment]
Hello,

Thank you for reporting this issue.
However, Storage Account resources do not support other than letters and numbers in their names.
https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftstorage

I'm closing this issue but feel free to add a comment if needed.

**Comment by Kumar9676** [comment]
Thanks for the answer.
