### ISSUE TITLE
[FEAT] ...Add an option to disable public access

### ISSUE THREAD

**Issue by morbendor** [claranet/terraform-azurerm-storage-account#14]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I've noticed that in the azurerm_storage_account resource, there's an option to disable public access by setting the public_network_access_enabled parameter to false. However, I couldn't find this option in your module.

I believe it would be beneficial to include this option in your module, as it provides more control and security over storage account access.

Thank you for considering my suggestion.

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_account

**Comment by BzSpi** [comment]
Hello @morbendor 

Thank you for opening this issue. 
Indeed, I'm also very surprised that the module does not support it, it would be a nice improvement. Do you think you'll be able to open a pull request with this new parameter ? 
We'll add it to our backlog but we cannot guarantee the implementation delay.
