### ISSUE TITLE
AzureRM 3.114.0  deprecated enable_https_traffic_only as  superseded by https_traffic_only_enabled

### ISSUE THREAD

**Issue by mloskot** [claranet/terraform-azurerm-storage-account#17]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://github.com/claranet/terraform-azurerm-storage-account/blob/506e7cb6851fc92e681adcd9b2463750d6c0ac5f/r-storage-account.tf#L20

triggers the deprecation warning:

```console
│ Warning: Argument is deprecated
│...
│   on .terraform/modules/stack_genesis.log_analytics.storage_logs/r-storage-account.tf line 20, in resource "azurerm_storage_account" "storage":
│   20:   enable_https_traffic_only        = var.nfsv3_enabled ? false : var.https_traffic_only_enabled
│
│ The property `enable_https_traffic_only` has been superseded by `https_traffic_only_enabled` and will be removed in v4.0 of the AzureRM Provider.
```

I'm opening this issue as reminder to update this module - I will try to submit PR after summer holidays period.

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_account

### References

- https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#31140-august-01-2024
- https://github.com/hashicorp/terraform-provider-azurerm/pull/26740

**Comment by davetustin** [comment]
I have also ran into this warning and was going to open an issue here to update it.

**Comment by Shr3ps** [comment]
Internal MR opened :), should be fixed/released this week

**Comment by mloskot** [comment]
Thank you!
