### ISSUE TITLE
[BUG] Example is not working

### ISSUE THREAD

**Issue by juan-acevedo-ntt** [claranet/terraform-azurerm-storage-account#5]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.55.0

### Affected Resource(s)/Data Source(s)

module.storage_account.azurerm_storage_account.storage

### Terraform Configuration Files

```hcl
If I try to deploy the example at `examples/main`, using the latest versions for all the Claranet modules, I get this error:


module.storage_account.azurerm_storage_account.storage: Creating...
╷
│ Error: creating Azure Storage Account "stmanolomanoloeuwdev": storage.AccountsClient#Create: Failure sending request: StatusCode=404 -- Original Error: Code="NotFound" Message="The resource 'xxx-xxx-xxx-xxx' does not exist."
│
│   with module.storage_account.azurerm_storage_account.storage,
│   on .terraform/modules/storage_account/r-storage-account.tf line 1, in resource "azurerm_storage_account" "storage":
│    1: resource "azurerm_storage_account" "storage" {
```

Where "xxx-xxx-xxx-xxx" is the ID of the tenant.
```


### Debug Output/Panic Output

```shell
https://gist.github.com/juan-acevedo-ntt/61a139c0b169f27592f8b9b321b4141f
```

### Expected Behaviour

Working example

### Actual Behaviour

Only the resource group is created

### Steps to Reproduce

- Change "x.x.x" in the example with current latest versions for each module
- make init
- make apply

**Comment by BzSpi** [comment]
Hello @juan-acevedo-ntt 

Thank you for the feedback, I can reproduce the issue.

**Comment by BzSpi** [comment]
@juan-acevedo-ntt you can remove the following code from the example to have the sample work.

```
  file_share_authentication = {
    directory_type = "AADDS"
  }
```

We will update the example accordingly & provide a fully working example for Azure Files authentication.

**Comment by juan-acevedo-ntt** [comment]
> @juan-acevedo-ntt you can remove the following code from the example to have the sample work.
> 
> ```
>   file_share_authentication = {
>     directory_type = "AADDS"
>   }
> ```
> 

Removing that code, it works. Thank you!

**Comment by BzSpi** [comment]
We have fixed and reworked a bit the example.

Thank you for notifying us about this.
